export { default as Home } from "./Home";
export { default as Details } from "./Details";
export { default as Login } from "./Login";
export { default as PropertyDetail } from "./PropertyDetail";
export { default as AddProperty } from "./AddProperty";
export { default as EditProperty} from "./EditProperty";
export { default as ProfilePage } from "./ProfilePage";
export { default as ProfileInfo } from "./ProfileInfo";
export { default as ProfileAppointment } from "./ProfileAppointment";
export { default as LikedProperties } from "./LikedProperties";